mysite/src/blog/urls.py
from django.urls import path, re_path

from blog import views
from blog.views import *


app_name = 'blog'

# views.클래스.as_view() - 제어단(control단) / name= - 템플릿단(view단)
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),
    
    # Example: /blog/post (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),
    
    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    
    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    
    # Example: /blog/arcive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    
    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    
    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    
    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    
    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    
    path('add/', views.PostCreateView.as_view(), name = 'add',),
    
    path('change/', views.PostChangeLV.as_view(), name = 'change',),
    
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name = 'update',),
    
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name = 'delete',),
]

mysite/src/bookmark/urls.py
from django.urls import path

from bookmark import views
from bookmark.views import BookmarkLV, BookmarkDV


app_name = 'bookmark' # 네임스페이스
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name = 'index'),
    
    path('<int:pk>', views.BookmarkDV.as_view(), name = 'detail'),
    
    path('add/', views.BookmarkCreateView.as_view(), name = 'add',),
    
    path('change/', views.BookmarkChangeLV.as_view(), name= 'change',),
    
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name = 'update',),
    
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name = 'delete',),
]

mysite/src/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView, UserCreateView, UserCreateDoneTV, ChatbotView,\
    CrawlerSearchFormView
from mysite.forms import CrawlerSearchForm



# from bookmark.models import Bookmark
# url 설계과정이 중요함.
# 리스트[] 속의 하나의 아이템이기 때문에 ','로 구분해줘야 함.
urlpatterns = [
    path('', HomeView.as_view(), name= 'home'),
    
    path('chatbot/', ChatbotView.as_view(), name= 'chatbot'),
    
    path('admin/', admin.site.urls),
    
    path('bookmark/', include('bookmark.urls')),
    
    path('blog/', include('blog.urls')),
    
    path('polls/', include('polls.urls')),
    
    path('photo/', include('photo.urls')),
    
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),
    
    path('crawling/', CrawlerSearchFormView.as_view(), name='crawling'), # crawling 구현관련 
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # media 파일 저장관련, pillow 다운필요.(파이썬 이미지 관리 패키지)


mysite/src/photo/urls.py
from django.urls.conf import path

from photo import views

app_name = 'photo'
urlpatterns = [
    #Example: /photo
    path('', views.AlbumLV.as_view(), name='index'),
    
    #Example: /photo/album/, same as /photo
    path('album', views.AlbumLV.as_view(), name='album_list'),
    
    #Example: /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),
    
    #Example: /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),
    
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),
]

mysite/src/polls/urls.py
from django.urls import path

from polls import views


app_name = 'polls'
urlpatterns=[
    path('', views.index, name='index'), # /polls/
    path('<int:question_id>/', views.detail, name='detail'), #/polls/5/
    path('<int:question_id>/results/', views.results, name='results'), #/polls/5/results/
    path('<int:question_id>/vote/', views.vote, name='vote'), #/polls/5/vote/
]

mysite/src/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    
    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px">

<!-- logo 이미지를 사용하기 위해서 static load -->
	{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-light fixed-top">
<!-- 'home' 메뉴를 없애고 로고가 그 기능을 수행. -->
    <span class="navbar-brand mx-4">
    	<a href="{% url 'home' %}">
    		<image src="{% static 'img/BigCarResque_Logo.png' %}" width="94" height="63">
    	</a>
    </span>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-dark" font-weight="bold" href="{% url 'blog:index' %}"><b>Blog</b></a></li>
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-dark" href="{% url 'photo:index' %}"><b>Photo</b></a></li>
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-dark" href="{% url 'polls:index' %}"><b>Polls</b></a></li>
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-dark" href="" onclick="openPopup()"><b>Q&A</b></a></li>
                
                <!-- 팝업창을 띄우는 소스 -->
                <script>
                	function openPopup(){
                		window.open("http://127.0.0.1:8000/chatbot/", "new", "menubar=no , width=490, height=720")
                	}
                </script>
            <li class="nav-item mx-1 btn btn-light">
                <a class="nav-link text-dark" href="{% url 'bookmark:index' %}"><b>Bookmark</b></a></li>

            <li class="nav-item dropdown mx-1 btn btn-light">
                <a class="nav-link dropdown-toggle text-dark" href="#" data-toggle="dropdown"><b>Add</b></a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
                    <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
                    <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
                </div>
            </li>

            <li class="nav-item dropdown mx-1 btn btn-light">
                <a class="nav-link dropdown-toggle text-dark" href="#" data-toggle="dropdown"><b>Change</b></a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'photo:album_change' %}">Album</a>
                    <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a>
                    <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
                </div>
            </li>
               
            <li class="nav-item dropdown mx-1 btn btn-light">
                <a class="nav-link dropdown-toggle text-dark" href="#" data-toggle="dropdown"><b>Util</b></a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                    <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                </div>
            </li>
        </ul>

        <form action="/crawling/" method="post">
       		{% csrf_token %}
       		<input type="text"  name="search_word" value="Crawling!!!">
       		<input type="submit"  value="Find" class="btn btn-dark btm-sm">
        </form>
        <ul class="navbar-nav ml-5 mr-5">
        	<li class="nav-item dropdown mx-1 btn btn-dark">
        		{% if user.is_active %}
        		<a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
        			<i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
        		</a>
        		<div class="dropdown-menu">
        			<a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        			<a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
        		</div>
        		{% else %}
        		<a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
        			<i class="fas fa-user"></i>&ensp;Anonymous&ensp;
        		</a>
        		<div class="dropdown-menu">
        			<a class="dropdown-item" href="{% url 'login' %}">Login</a>
        			<a class="dropdown-item" href="{% url 'register' %}">Register</a>
        		</div>
        		{% endif %}
        	</li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}
	<footer class="fixed-bottom bg-dark">
	    <div class="text-white font-italic text-right mr-5">Contact Big Cat Rescue -> info@bigcatrescue.org&nbsp;&nbsp;&nbsp;or&nbsp;&nbsp;&nbsp;call 813.920.4130</div>
	</footer>
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/c998a172fe.js"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

mysite/src/templates/chatbot.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Big Cat Resque - [Q&A] Chabot</title>

</head>
<body>
	<iframe class="chatbot"
	    allow="microphone;"
	    width="470"
	    height="690"
	    src="https://console.dialogflow.com/api-client/demo/embedded/f27fb05f-f8b4-427f-a8c2-ad8933ce3ef7">
	</iframe>
</body>
</html>

mysite/src/templates/crawling.html
{% extends "base.html" %}
{% block title %}crawling.html{% endblock %}


{% block content %}
<style>
	.image-container {
        overflow: hidden;
        display: flex;
        align-items: center;
        justify-content: center;
		width:190px;
		height:160px;
		border: 1px solid #d3d3d3;
		border-collapse:separate;
	}
</style>

<br/>
<h1>구글 이미지 검색 기반 - Crawling</h1>
<hr>
<form action="." method="post">
<!-- '{% csrf_token %}'는 폼태그 첫 출에 항상 입력해야 함. -->
{% csrf_token %}

</form>
	<div class="container">
		<div class="row">
		{% autoescape off %}
		
			{% for item in last_List %}
				{{ item }}
			{% endfor %}
		
		{% endautoescape %}
		</div>
	</div>

<br/>
<br/>
<br/>
{% endblock %}

mysite/src/templates/home.html
<!DOCTYPE html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<title>Big Cat Rescue</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
	{% extends 'base.html' %}
	
	{% block extra-style %}
	<style type="text/css">
	.home-image {
	    background-position: center;
	    background-size: 100%;
	    height: 500px;
	}
	.title {
	    color: #c80;
	    font-weight: bold;
	}
	.powered {
	    position: relative;
	    top: 77%;
	    color: #cc0;
	    font-style: italic;
	}
	</style>
	{% endblock %}
	
	{% block content %}
	    <div class="home-image">
	    <!-- 기존 이미지 대신에 유튜브 영상 넣고 자동으로 재생 및 음소거 되게함.(유튜브 영상의 src 값 뒤에 "?autoplay=1&mute=1"를 붙이는게 핵심.) -->
		    <iframe 
		    	width="100%" 
		    	height="500" 
		    	src="https://www.youtube.com/embed/87aJgGqYsSk?autoplay=1&mute=1" 
		    	title="YouTube video player" 
		    	frameborder="0" 
		    	allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
		    	allowfullscreen
		    ></iframe>
	    </div>
	    
	    <hr style="margin: 10px 0;">
	
	    <div>
	    	<!-- "<div class="col-sm-6">"의 클래스를 "col-sm-3"으로 수정하면 됨. -->
	        <div>
	            <h1>Who is Big Cat Rescue?</h1>
	            <p>Big Cat Rescue is one of the largest accredited sanctuaries
	            in the world dedicated to abused and abandoned big cats.</p>
	            
	            <p></p>
	            
	            <p>We are home to about 50+ lions, tigers, bobcats, cougars
	            and other species most of whom have been abandoned, abused,
	            orphaned, saved from being turned into fur coats, or retired from performing acts.</p>
	              
	            <p>What sets Big Cat Rescue apart is that we are working to end
	            the abuse at its root by ending the private possession and trade
	            in exotic cats through legislation and education.</p>
	             
	            <p>The sanctuary began rescuing exotic cats in Nov. 4, 1992.</p>
	        </div>
	        <br>
	        
	        <div>
	            <h3>Mission Statement</h3>
	            <p>Big Cat Rescue’s mission is to provide the best home we can for the cats in our care,
	            end abuse of big cats in captivity and prevent extinction of big cats in the wild.</p>
	        </div>
	        <br>
	        
	        <div>
	        	<h3>Big Cat Rescue has many species of cats,<br> many of whom are threatened, endangered or extinct now in the wild, including:</h3>
	        	<p>Tigers, Lions, Leopards, Cougars, Bobcats, Lynx, Servals, Ocelots and Caracals</p>
	        </div>
	        <br>

	        <div>
	        	<h3>The cats at Big Cat Rescue are here for a variety of reasons, including:</h3>
	        	<p>Abandoned by owners who wrongly thought they would make good pets</p>
	        	<p>Abused by owners in order to force them to perform</p>
	        	<p>Retired from performing acts</p>
	        	<p>Saved from being slaughtered to make fur coats</p>
	        	<p>Rescued as babies after hunters killed their mothers</p>
	        </div>
	        <br>
	        
	        <div>
	        	<h3>Contact Big Cat Rescue</h3>
	        	<p>General inquiries: info@bigcatrescue.org or call 813.920.4130<br>
	        	We are located at 12802 Easy St. Tampa, FL 33625 No visitors other than regular donors.</p>
	        </div>
	        <hr>
	        <br>
	    </div>
	{% endblock content %}
</body>
</html>