mysite/src/blog/urls.py
from django.urls import path, re_path

from blog import views
from blog.views import *


app_name = 'blog'

# views.클래스.as_view() - 제어단(control단) / name= - 템플릿단(view단)
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),
    
    # Example: /blog/post (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),
    
    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    
    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    
    # Example: /blog/arcive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    
    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    
    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    
    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    
    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    
    path('add/', views.PostCreateView.as_view(), name = 'add',),
    
    path('change/', views.PostChangeLV.as_view(), name = 'change',),
    
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name = 'update',),
    
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name = 'delete',),
]

mysite/src/bookmark/urls.py
from django.urls import path

from bookmark import views
from bookmark.views import BookmarkLV, BookmarkDV


app_name = 'bookmark' # 네임스페이스
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name = 'index'),
    
    path('<int:pk>', views.BookmarkDV.as_view(), name = 'detail'),
    
    path('add/', views.BookmarkCreateView.as_view(), name = 'add',),
    
    path('change/', views.BookmarkChangeLV.as_view(), name= 'change',),
    
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name = 'update',),
    
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name = 'delete',),
]

mysite/src/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView, UserCreateView, UserCreateDoneTV, ChatbotView,\
    CrawlerSearchFormView
from mysite.forms import CrawlerSearchForm



# from bookmark.models import Bookmark
# url 설계과정이 중요함.
# 리스트[] 속의 하나의 아이템이기 때문에 ','로 구분해줘야 함.
urlpatterns = [
    path('', HomeView.as_view(), name= 'home'),
    
    path('chatbot/', ChatbotView.as_view(), name= 'chatbot'),
    
    path('admin/', admin.site.urls),
    
    path('bookmark/', include('bookmark.urls')),
    
    path('blog/', include('blog.urls')),
    
    path('polls/', include('polls.urls')),
    
    path('photo/', include('photo.urls')),
    
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),
    
    path('crawling/', CrawlerSearchFormView.as_view(), name='crawling'), # crawling 구현관련 
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # media 파일 저장관련, pillow 다운필요.(파이썬 이미지 관리 패키지)


mysite/src/bookmark/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
# vo 클래스
    # 'models.Model'를 반드시 상속받아야 한다.
class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True) # 'TITLE'자리 - verbose_name 입력.
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    
    # 객체표현 양식 - Java의 tostring()
    def __str__(self):
        return self.title
    

mysite/src/bookmark/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls.base import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from bookmark.models import Bookmark
from mysite.views import OwnerOnlyMixin


# Create your views here.
class BookmarkLV(ListView):
    model = Bookmark
    template_name = 'bookmark/bookmark_list.html'
    
class BookmarkDV(DetailView):
    model = Bookmark
    template_name = 'bookmark/bookmark_detail.html'
    
class BookmarkCreateView(LoginRequiredMixin, CreateView):    
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        
        return super().form_valid(form)
    
class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'
    
    def get_queryset(self):
        return Bookmark.objects.filter(owner = self.request.user)
    
class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')
    
class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

mysite/src/bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}

	<br>
	<h1>Bookmark Change - {{ user }}</h1>
	<hr>
	<br>
	
	<table class="table table-bordered table-condensed table-striped">
	
		<thead>
			<tr class="table-primary">
				<th>Title</th>
				<th>Url</th>
				<th>Owner</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>
		</thead>
		
	
		<tbody>
			{% for item in object_list %}
			<tr>
				<td>{{ item.title }}</td>
				<td>{{ item.url }}</td>
				<td>{{ item.owner }}</td>
				<td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
				<td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
			</tr>
			{% endfor %}
		</tbody>
	
	</table>

{% endblock %}	

mysite/src/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}

	<h1>Bookmark Delete</h1>
	<br>
	
	<form action="." method="post">
		{% csrf_token %}
		<p>Are you sure you want to delete "{{ object }}" ?</p>
		<input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
	</form>
	
{% endblock %}

mysite/src/bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html'%}
{% block title %}Recommendation Detail{% endblock %}
{% block content %}
<div id = "content">
	<h1>Recommendation</h1>
	<hr>
	
	<h5>{{object.title}}</h5>
	
	<b>
		&emsp; - <a href = "{{object.url}}" style="text-decoration:none; color:black;">{{object.url}}</a>
	</b>
		
</div>
{% endblock %}

mysite/src/bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}bookmark_form.html{% endblock %}

{% block content %}

	<br>
	<h1>Bookmark Create/Update - {{ user }}</h1>
	<i>&emsp;- This is a creation or update form for your bookmark.</i>
	<br>
	<br>
	
	{% if form.errors %}
	<div class="alert alert-danger">
		<div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
		{{ form.errors }}
	</div>
	{% endif %}
	
	<form action="." method="post" class="card pt-3">
	{% csrf_token %}
		<div class="form-group row">
			{{form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
			
			<div class="col-sm-5">
				{{ form.title|add_class:"form-control"|attr:"autofocus" }}
			</div>
			
		</div>
	
		<div class="form-group row">
			{{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
			
			<div class="col-sm-5">
				{{ form.url|add_class:"form-control" }}
			</div>
		
		</div>
		
		<div class="form-group">
		
			<div class="offset-sm-2 col-sm-5">
				<input type="submit" value="Submit" class="btn btn-info"/>
			</div>
			
		</div>
	
	</form>
	
{% endblock %}

mysite/src/bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html'%}
{% block title %}Django Bookmark List{% endblock %}
{% block content %}
<div id = "content">
	<br>
	<h1>Recommendation List</h1>
	<hr>

	<h5></h5>
	
	<ol>
		{% for bookmark in object_list %}
			<b>
				<li>
					<a href = "{% url 'bookmark:detail' bookmark.id %}" style="text-decoration:none; color:black;">
						{{bookmark}}
					</a>
				</li>
			</b>
			<br>
		{% endfor %}
	</ol>
</div>
{% endblock %}