mysite/src/blog/urls.py
from django.urls import path, re_path

from blog import views
from blog.views import *


app_name = 'blog'

# views.클래스.as_view() - 제어단(control단) / name= - 템플릿단(view단)
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),
    
    # Example: /blog/post (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),
    
    # Example: /blog/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    
    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    
    # Example: /blog/arcive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    
    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    
    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    
    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    
    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    
    # Example: /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    
    path('add/', views.PostCreateView.as_view(), name = 'add',),
    
    path('change/', views.PostChangeLV.as_view(), name = 'change',),
    
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name = 'update',),
    
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name = 'delete',),
]

mysite/src/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView, UserCreateView, UserCreateDoneTV, ChatbotView,\
    CrawlerSearchFormView
from mysite.forms import CrawlerSearchForm



# from bookmark.models import Bookmark
# url 설계과정이 중요함.
# 리스트[] 속의 하나의 아이템이기 때문에 ','로 구분해줘야 함.
urlpatterns = [
    path('', HomeView.as_view(), name= 'home'),
    
    path('chatbot/', ChatbotView.as_view(), name= 'chatbot'),
    
    path('admin/', admin.site.urls),
    
    path('bookmark/', include('bookmark.urls')),
    
    path('blog/', include('blog.urls')),
    
    path('polls/', include('polls.urls')),
    
    path('photo/', include('photo.urls')),
    
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),
    
    path('crawling/', CrawlerSearchFormView.as_view(), name='crawling'), # crawling 구현관련 
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # media 파일 저장관련, pillow 다운필요.(파이썬 이미지 관리 패키지)


mysite/src/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse  # url 패턴을 만들어 준다.
from django.utils.text import slugify
from taggit.managers import TaggableManager

from photo.fields import ThumbnailImageField


# Java의 'vo'클래스의 기능
# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name = 'TITLE', max_length = 50)
    
    slug = models.SlugField('SLUG', unique = True, allow_unicode = True, help_text = 'one word for title alias.')
    
    description = models.CharField('DESCRITPTION', max_length = 100, blank = True, help_text = 'simple description text.')
    
    content = models.TextField('CONTENT')
    
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add = True)
    
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now = True)
    
    tags = TaggableManager(blank=True)
    
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    image = ThumbnailImageField('IMAGE', upload_to='blog/%Y/%m', null=True) # image 추가
    
    # 이너 클래스
    class Meta:
        verbose_name = 'post'
        # 'verbose_name_plural' -> 복수명칭
        verbose_name_plural = 'posts'
        # 'db_table' -> 테이블 명을 명시하면 임의로 설정 가능.
        db_table = 'blog_posts'
        # 'ordering = ('+/-modify_dt',)' -> '+'면 오름차순, '-'면 내림차순 ','는 자료의 다량일때를 위해 있는 것
        # ordering = ('-modify_dt',) # id 순으로 정렬하기 위해서 주석처리.
        ordering = ('-id',) # id순으로 내림차순 정렬.
        
    # 객체를 표현하는 방식    
    def __str__(self):
        return self.title
    
    # 'url'을 리턴하는 방식
    def get_absolute_url(self):
        return reverse('blog:post_detail', args = (self.slug,))
    
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    
    def get_next(self):
        return self.get_next_by_modify_dt()
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

mysite/src/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

mysite/src/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q  # 검색기능 관련(색인)
from django.shortcuts import render  # 검색기능 관련
from django.urls.base import reverse_lazy
from django.views.generic import FormView  # 검색기능 관련
from django.views.generic import ListView, DetailView
from django.views.generic.base import TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from blog.forms import PostSearchForm  # 검색기능 관련
from blog.models import Post
from mysite import settings  # 댓글기능 추가 시 임포트
from mysite.views import OwnerOnlyMixin


# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    
    # 페이지 당 몇개의 글을 보여줄지 지정하는 모듈 
    paginate_by = 15
    
class PostDV(DetailView):
    model = Post
    
    # 댓글기능 추가를 위한 함수.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}-{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}"
        return context
    
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'
    
class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    
class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    
class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    
class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

# 태그와 관련된 오브젝트를 리스트로 보여줌.(VO의 형태) 
class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post
    
    # self는 'TaggedObjectLV'를 의미.
    def get_queryset(self):
        # 'self.kwargs.get('tag')'로 filter하겠다.
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))
    
    # **를 붙여줘야 dict형태로 리턴(*면 list형태)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 'tagname'이라는 키로 인덱싱
        context['tagname'] = self.kwargs['tag']
        return context
    
# 검색기능 추가로 인해 작성한 class
class SearchFormView(FormView):
    form_class = PostSearchForm # blog.forms 생성
    template_name = 'blog/post_search.html'
    
    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        
        # Post는 blog의 vo클래스
        post_list = Post.objects.filter(
                Q(title__icontains=searchWord) 
              | Q(description__icontains=searchWord) 
              | Q(content__icontains=searchWord)
        ).distinct() # distinct()는 중복을 배제
        
        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list
        
        return render(self.request, self.template_name, context)
    
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content','image', 'tags'] # image 추가
    initial = {'slug': 'auto-filling-do-not-input'}
    #fields = ['title', 'description', 'content', 'tags'] # slug 필드 처리 방법2
    success_url = reverse_lazy('blog:index')
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        
        return super().form_valid(form)
    
class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'
    
    def get_queryset(self):
        
        return Post.objects.filter(owner = self.request.user)
    
class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'image', 'tags'] # image 추가
    success_url = reverse_lazy('blog:index')
    
class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

mysite/src/blog/templates/blog/post_all.html
{% extends 'base.html'%}

{% block title %}Big Cat Rescue - Blog List{% endblock %}

{% block content %}

	<br>
	<h1>Blog List</h1>
	<hr>
	
	<table class="table table-hover table-sm table-condensed">
		
		<thead>
		
			<tr class="table bg-dark text-white text-center">
				<th>No.</th>
				<th>Post Title</th>
				<th>Written by</th>
				<th>Modify Date</th>
			</tr>
			
		</thead>
		
		<tbody>
		
			{% for post in posts %}
			
			<tr>
				<td class="text-center" style="width:100px">{{ post.id }}</td>
				<td style="width:600px; text-indent:1em;"><a href='{{ post.get_absolute_url }}' style="text-decoration:none; color:black;">{{ post.title }}</a></td>
				<td class="text-center " style="width:150px">{{ post.owner }}</td>
				<td class="text-center " style="width:150px">{{ post.modify_dt|date:"N d, Y" }}</td>
			</tr>
			
			{% endfor %}
			
		</tbody>
		
	</table>
		
	<br>
	
	<div class="row">
		
		<div class="col-md-6 text-light">
		
			{% if page_obj.has_previous %}
				<a href= "?page= {{ page_obj.previous_page_number }}">
				<i class="fas fa-arrow-circle-left"></i> Pre</a>			
			{% endif %}
			
		</div>

		<div class="col-md-6 text-right">	
				
			{% if page_obj.has_next %}
				<a href= "?page= {{ page_obj.next_page_number }}">
				Next <i class="fas fa-arrow-circle-right"></i></a>
			{% endif %}

		</div>
		
	</div>	
	
	<div class="text-center">
	
		page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
			
	</div>
	
	<hr>
	<br>
	<br>			
	<br>
	<br>
	<br>

{% endblock %}

mysite/src/blog/templates/blog/post_archive.html
{% extends 'base.html'%}
{% block title %}Post Archives - Main{% endblock %}
{% block content %}

	<br>
	<h1>Post Archives until {% now "N d, Y" %}</h1>
	<hr>

	<div>	
	{% for date in date_list %}
	<p>
		<b>
			<a href = "{% url 'blog:post_year_archive' date|date:'Y' %}" style="text-decoration:none; color:black;">
				&emsp;- Year {{date|date:"Y"}}
			</a>
		</b>
	</p>
	{% endfor %}	
	</div>	
		
	<b>
		&ensp;Post Modify Date&emsp;&emsp;&emsp;Post Title
	</b>

	<div>	
		<ul>
			{% for post in object_list %}
			<li>
				{{ post.modify_dt|date:"Y-m-d" }}
				&emsp;&emsp;&ensp;
				<a href = "{{ post.get_absolute_url }}" style="text-decoration:none; color:black;">
					{{ post.title }}
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>	
	
	<br>
	<br>
	<hr>	
	<br>
{% endblock %}

mysite/src/blog/templates/blog/post_archive_day.html
{% extends 'base.html'%}
{% block title %}Post Archives for Date{% endblock %}
{% block content %}
	<br>
	<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
	<hr>
		
	<b>
		&ensp;Post Modify Date&emsp;&emsp;&emsp;Post Title
	</b>	
			
	<div>
		<ul>
			{% for post in object_list %}
			<li>{{ post.modify_dt|date:"Y-m-d" }}
				&emsp;&emsp;&ensp;
				<a href = "{{ post.get_absolute_url }}" style="text-decoration:none; color:black;">
					{{ post.title }}
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>

	<br>
	<br>
	<hr>	
	<br>
{% endblock %}

mysite/src/blog/templates/blog/post_archive_month.html
{% extends 'base.html'%}
{% block title %}Post Archives for - Month{% endblock %}
{% block content %}

	<br>
	<h1>Post Archives for {{ month|date:"N Y" }}</h1>
	<hr>	

	<b>
		&ensp;Post Modify Date&emsp;&emsp;&emsp;Post Title
	</b>
	
	<div>
		<ul>
			{% for post in object_list %}
			<li>{{ post.modify_dt|date:"Y-m-d" }}
				&emsp;&emsp;&emsp;
				<a href = "{{ post.get_absolute_url }}" style="text-decoration:none; color:black;">
					{{ post.title }}
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>
	
	<br>
	<br>
	<hr>	
	<br>
{% endblock %}

mysite/src/blog/templates/blog/post_archive_year.html
{% extends 'base.html'%}
{% block title %}Post Archives - Year{% endblock %}
{% block content %}

	<br>
	<h1>Post Archives for {{ year|date:"Y"}}</h1>
	<hr>

	<ul>
		{% for date in date_list %}
		<li style = "display: inline;">
			<b>
				<a href = "{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}" style="text-decoration:none; color:black;">
					{{ date|date:"F" }}
				</a>
			</b>
		</li>
		{% endfor %}
	</ul>
	
	<b>
		&ensp;Post Modify Date&emsp;&emsp;&emsp;Post Title
	</b>	
	
	<div>
		<ul>
			{% for post in object_list %}
			<li>{{ post.modify_dt|date:"Y-m-d" }}
			&emsp;&emsp;&ensp;
				<a href = "{{ post.get_absolute_url }}" style="text-decoration:none; color:black;">
					{{ post.title }}
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>
	
	<br>
	<br>
	<hr>	
	<br>
{% endblock %}

mysite/src/blog/templates/blog/post_change_list.html
{% extends "base.html" %}

{% block title %}post_change_list.html{% endblock %}

{% block content %}

	<br>
	<h1>Post Change - {{ user }}</h1>
	<hr>
	<br>
	
	<table class="table table-bordered table-sm table-striped">
		
		<thead>
			<tr class="table-primary">
				<th>Title</th>
				<th>Description</th>
				<th>Owner</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>
		</thead>
		
		<tbody>
			{% for item in object_list %}
			<tr>
				<td>{{ item.title }}</td>
				<td>{{ item.description }}</td>
				<td>{{ item.owner }}</td>
				<td><a href="{% url 'blog:update' item.id %}">Update</a></td>
				<td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
			</tr>
			{% endfor %}
		</tbody>
		
	</table>
	
{% endblock %}

mysite/src/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}
	<br>
	<h1>Post Delete</h1>
	<hr>
	<br>
	
	<form action="." method="post">
		{% csrf_token %}
		
		<p>Are you sure you want to delete "{{ object }}" ?</p>
		
		<input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
		
	</form>
	
{% endblock %}

mysite/src/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}Big Cat Rescue - Blog Detail{% endblock %}

{% block extra-style %}
<style>
.post-body {
    width: 80%;
    margin: auto;
    font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    font-size: 16px;
}
</style>
{% endblock extra-style %}

{% block content %}
<div class="post-body">

    <h2>{{ object.title }}</h2>

	<div class="row">
		
		<div class="col-md-6 text-light">
		
			{% if object.get_previous %}
				<a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
				<i class="fas fa-arrow-circle-left"></i> {{ object.get_previous }}</a>
			{% endif %}
			
		</div>
		
		<div class="col-md-6 text-right">	
		
			{% if object.get_next %}
				<a href="{{ object.get_next.get_absolute_url }}" title="View next post">
			{{ object.get_next }} <i class="fas fa-arrow-circle-right"></i>
			</a>
			{% endif %}

		</div>

    </div>

    <div>{{ object.modify_dt|date:"j F Y" }}</div>
    <br>

	<div class="col-md-9">
		<a href="{{ object.image.url }}" >
			<img src="{{ object.image.url }}" style="width: 100%;">
		</a>
	</div>


    <div>
        {{ object.content|linebreaks }}
    </div>

    <br>
    <div>
        <b>TAGS</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %}
        {% get_tags_for_object object as "tags" %}
        {% for tag in tags %}
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
&emsp;
        <a href="{% url 'blog:tag_cloud' %}"> <span class="btn btn-info btn-sm">TagCloud</span> </a>
    </div>

    <br>
    <div id="disqus_thread"></div>

</div>
<br>
<br>
{% endblock %}

{% block extra-script %}
<script>
/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION
*  BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT:
*  https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
    this.page.identifier = '{{ disqus_id }}';
    this.page.url = '{{ disqus_url }}';
    this.page.title = '{{ disqus_title }}';
};

(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://{{ disqus_short }}.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

mysite/src/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}post_form.html{% endblock %}

{% block content %}

	<br>
	<h1>Post Create/Update - {{ user }}</h1>
	<i>&emsp;- This is a creation or update form for your post.</i>
	<br>
	<br>
	
	{% if form.errors %}
	<div class="alert alert-danger">
	
		<div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
		{{ form.errors }}
	
	</div>
	{% endif %}

	{% if form.is_multipart %}
	<form enctype="multipart/form-data" action="" method="post" class="card pt-3">
	{% else %}
	<form action="." method="post" class="card pt-3">
	{% endif %}
	{% csrf_token %}
		<div class="form-group row">
			{{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
			
			<div class="col-sm-5">
				{{ form.title|add_class:"form-control"|attr:"autofocus" }}
			</div>
			
		</div>
		
		<div class="form-group row">
			{{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
			
			<div class="col-sm-5">
				{{form.slug|add_class:"form-control"|attr:"readonly" }}
			</div>
			
			<small class="form-text text-muted">{{ form.slug.help_text }}</small>
			
		</div>
		
		<div class="form-group row">
			{{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
			
			<div class="col-sm-5">
				{{ form.description|add_class:"form-control" }}
			</div>
			
			<small class="form-text text-muted">{{ form.description.help_text }}</small>
			
		</div>
		
		<div class="form-group row">
			{{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
			
			<div class="col-sm-5">
				{{ form.content|add_class:"form-control" }}
			</div>
			
		</div>

		<div class="form-group row">
			{{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
			
			<div class="col-sm-5">
				{{ form.image|add_class:"form-control-file" }}
			</div>
			
		</div>	
		
		<div class="form-group row">
			{{ form.tags|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
		
			<div class="col-sm-5">
				{{ form.tags|add_class:"form-control" }}
			</div>
			
			<small class="form-text text-muted">{{ form.tags.help_text }}</small>
		
		</div>
		<div class="form-group">
			
			<div class="offset-sm-2 col-sm-5">
				<input type="submit" value="Submit" class="btn btn-info"/>
			</div>
			
		</div>
		
	</form>

{% endblock %}

mysite/src/blog/templates/blog/post_search.html
{% extends "base.html" %}
{% block title %}Post Search{% endblock %}
{% block content %}
<br>
<h1>Post Search</h1>
<hr>
<br>

<form action="." method="post">
<!-- '{% csrf_token %}'는 폼태그 첫 출에 항상 입력해야 함. -->
{% csrf_token %}
{{ form.as_table }}
<input type="submit" value="Search" class="btn btn-info btn-sm">
</form>
<br/>
<br/>

<br/>
{% if object_list %}
<h2>Search Result</h2>
	{% for post in object_list %}
	<h3><a href="{{post.get_absolute_url}}" style="text-decoration:none; color:black;">{{ post.title }}</a></h3>
	<h5>(Modify Date: {{post.modify_dt|date:"N d, Y"}})</h5>
	&nbsp;{{post.description}}
	<br>
	<br>
	{% endfor %}
{% elif search_term %}
	<b>
		<i>Search Word({{search_term}}) Not Found !</i>
	</b>
{% endif %}
{% endblock %}